import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import '@formio/js/dist/formio.full.min.css';
import dynamic from 'next/dynamic'

const FormBuilder = dynamic(() => import('@formio/react').then(module => module.FormBuilder), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {typeof window === "undefined" ? null : (
          <FormBuilder
            form={{
              display: "form",
              components: [
                {
                  label: "Email",
                  tableView: true,
                  key: "email",
                  type: "email",
                  input: true,
                },
                {
                  label: "Password",
                  tableView: false,
                  key: "password",
                  type: "password",
                  input: true,
                  protected: true,
                },
              ],
            }}
          />
        )}
      </main>
    </>
  );
}
